### PR TITLE
Trying to fix missing C and V file actions

### PR DESCRIPTION
**Pull request by linzhp**
I don't really understand what the code did, but the code caused a lot of C and V actions missing from file revisions.

@jgbarah @andygrunwald Any comments?

### CODE REVIEW

**Comment by andygrunwald** [comment]
I do not understand this part of code as well.
But it seems to be that this is not needed.

The regarding commit from 2009-09-28 "Add FileRevs to iterate over the list of files and revisions" got no useful information for this.

I would suggest to merge this.
What do you think @jgbarah @sduenas ?

**Comment by andygrunwald** [comment]
@linzhp can you provide a small instruction how i can test this? Which extensions has to enabled?
What is the output / database value before and what is expected?

**Comment by linzhp** [comment]
One way to test it is to use `content` extension. The extension uses FileRevs, and extract file content for each revision. So for each action in `actions` table, if it changes a code file, there should be a content table entry for it.
However, content entries for a lot of C and V actions were missing without the change in this PR, because those revisions were not returned by FileRevs.

**Comment by sduenas** [comment]
I don't understand the code either, I'm going to ask Carlos about it, probably he remembers why this code was added.

**Comment by andygrunwald** [comment]
It would be great to get deeper insights into this peace of code.
But maybe it was just for some research reasons.
Looking forward to a good Argument or to a merge of this change

Am Sonntag, 2. März 2014 schrieb Santiago Dueñas :

**Comment by sduenas** [comment]
Carlos doesn't remember anything about what the code does, either.

I suggest to apply this change. If it breaks something, we can always go back reverting the commit. What do you think?

**Comment by andygrunwald** [comment]
From my point of you: +1 for this way.

Am Dienstag, 4. März 2014 schrieb Santiago Dueñas :

**Comment by jgbarah** [comment]
+1, @sduenas

**Comment by sduenas** [comment]
Ok. Done!

**Comment by linzhp** [comment]
Thank you guys!

**Comment by sduenas** [comment]
Hey guys. See issue #85 . I found why this code was needed.

**Pull request merged**
