### PR TITLE
Pysqlite2.apidb2 replaced by sqlite3

### PR DESCRIPTION
**Pull request by carlos-gs**
Pysqlite2.apidb2 references were changed by sqlite3 that reference to python standar library.

### CODE REVIEW

**Comment by andygrunwald** [comment]
Hey @carlos-gs,

thanks for your pull request. At a first small check it looks really good. Thanks to move this forwards ;)

Did you get an official resource (link, blog post, mailing list entry, etc.) where is documented that Pysqlite2.apidb2 is deprecated?
Or is there a way to "enable" deprecation errors? If yes, how?

I`am "quite new" to the python world / community. This is the reason for my link request.

**Comment by carlos-gs** [comment]
You did well asking me it, I've said too fast 'deprecated' to summarize at the last description, I haven't careful enough about it and I've thought it while I was reading about your doubts. It's my fault of newbie =)

How I said and I linked in mail list last week (http://docs.python.org/2/library/sqlite3.html), python 2.5 and later include a dbapi2 interface library and it maybe be more convenient use it. It will depend much of support to pysqlite2 library from each linux dist. This is the true discussion, I think.

Thanks for your attention.

**Comment by sduenas** [comment]
I suggest to proceded with the change.

I've googling a little and I didn't find any good reason to continue using pysqlite2. The only problem is if someone uses versions prior to Python 2.5, but IMHO, 99.99% of CVSAnalY users neither use Python <= 2.4 nor the sqlite driver.

What do you thinkg @andygrunwald?

**Comment by andygrunwald** [comment]
@sduenas i propose to proceed the change, too.
Thanks for the contribution @carlos-gs!

I think we should add the min. req. version of Python 2.5 to the requirements in the README file, to avoid new issues regarding the python version. Further more i suggest to raise the version for the next CVSAnaly release, because of the new python version requirement.
What are your opinions?

So @sduenas feel free to merge it :)

**Comment by sduenas** [comment]
@andygrunwald I've just updated README.md, as you suggested.

**Pull request merged**
