### PR TITLE
Add a special case to GitParser to deal with WordPress contributions

### PR DESCRIPTION
**Pull request by rodrigoprimo**
As discussed on the mailing list, WordPress identifies code contributions made by developers without access to the repository with a tag "props" followed by the user name on the commit message. This PR changes GitParser behavior when dealing with WordPress repo to identify the contributor as the author of the commit as suggested by Germán Poo-Caamaño.

### CODE REVIEW

**Comment by rodrigoprimo** [comment]
I realized that the way I implemented this works only if the tag "props" and the user name are on the same line which is not always the case. Thus I'm closing this PR and I will open another one when I find a way to support all scenarios.

**Comment by andygrunwald** [comment]
Thanks @rodrigokuroda!
If you need help just let me know how i can support here.

**Comment by rodrigoprimo** [comment]
@andygrunwald I couldn't find an easy way to get the full commit message with the current structure of CVSAnalY. I could only get one line per time.

This PR is able to correctly identify a contribution in this format `props @rodrigoprimo` but is unable to identify it in a multiline format:

```
props
@rodrigoprimo
```

Any ideas?

**Comment by andygrunwald** [comment]
Sorry for the late reply @rodrigoprimo

I don`t tested to crawl wordpress for now, but i think a better way to solve this is to write an extension for wordpress. See available extensions at https://github.com/MetricsGrimoire/CVSAnalY/tree/master/pycvsanaly2/extensions

**Comment by rodrigoprimo** [comment]
Thanks @andygrunwald. I will check the extension system.

**Pull request closed without merging**
