### PR TITLE
Added commit graph

### PR DESCRIPTION
**Pull request by linzhp**
Hi CVSAnalY team,

I decided to put my new changes to CVSAnalY instead of MininGit. This is my first batch of changes. It adds a commit graph to keep track of parents of commits. This commit graph currently only supports Git, as it is not necessary in Subversion and CVS. Hope someone could implement a Bzr version if it is necessary (I am not familiar with Bzr).

With regards to #1, I will pick features that I am actively using from MininGit and merge them into CVSAnalY incrementally, instead of merging all changes at once.

### CODE REVIEW

**Comment by jgbarah** [comment]
Thanks a lot! This is something very much needed. The code seems ok, but I have to have a look at its interactions with the incremental retrieval of information from the git repo. I hope that won't take long time.

**Comment by andygrunwald** [comment]
@jgbarah any new information here?

**Comment by andygrunwald** [comment]
@linzhp Can you rebase this PR?
Then i will it give a try to test :)

**Comment by linzhp** [comment]
Rebased

**Comment by andygrunwald** [comment]
Hey @linzhp,

thanks for this awesome contribution.
I`ve checked this (with executing it with + without your changes + checking the commit_graph table). It works fine. Thanks :)

**Pull request merged**
