### PR TITLE
Git noref

### PR DESCRIPTION
**Pull request by maelick**
I have added a CLI argument to parse only the master branch for git repositories. Also see [this pull request](https://github.com/MetricsGrimoire/RepositoryHandler/pull/9).

### CODE REVIEW

**Comment by jgbarah** [comment]
In case we add a parameter, maybe it would be better to let it specify a branch name, so that it would be useful not only for master.
I would also like to see some use cases, since it is not difficult to get actions in master by selecting that branch in the database produced after reading the whole log.
In any case, I don't think this would be harmful, we could pull it as is, and discuss the rest later. Other opinions?

**Comment by maelick** [comment]
Good idea to let the user specify the branch name, I have proposed modifications with this instead of a single boolean parameter.

As a use case, if you only care about the master branch in a big repository like evolution, it significantly improves CVSAnaly execution time and reduces database size.

**Comment by andygrunwald** [comment]
Thanks @maelick for your contribution. And thanks @jgbarah for your comments.
Afaik this PR can be closed right? Because https://github.com/MetricsGrimoire/CVSAnalY/pull/51 is the new one, right?
If yes i will close this one and we will continue in https://github.com/MetricsGrimoire/CVSAnalY/pull/51.

**Comment by andygrunwald** [comment]
I will close this, because this is the previous version of https://github.com/MetricsGrimoire/CVSAnalY/pull/51.

If i am wrong, please inform me with a comment

**Pull request closed without merging**
