### PR TITLE
Add support for timezones of git log messages

### PR DESCRIPTION
**Pull request by andygrunwald**
This PR solves https://github.com/MetricsGrimoire/CVSAnalY/issues/63

The timezone is saved in seconds. Some examples:

```
CommitDate: Sun Apr 20 18:33:46 2014 +0200
=> 7200 (Germany)

CommitDate: Tue Feb 11 22:10:39 2014 -0800
=> -28800 (USA, California, Santa Cruz)

CommitDate: Sun Apr 20 16:07:36 2014 +0530
=> 19080 (India)
```

If you ran CVSAnaly on MySQL you can migrate your database with the queries:

``` sql
ALTER TABLE scmlog 
  ADD COLUMN date_tz INT AFTER date,
  ADD COLUMN author_date_tz INT AFTER author_date;
```

@linzhp maybe this is useful for you as well?

### CODE REVIEW

**Comment by linzhp** [comment]
Why do you want to convert the timezone into seconds? Isn't something like "+0200" more readable?

**Comment by andygrunwald** [comment]
This was the idea from @jgbarah, because the same approach is used in [MailingListStats](https://github.com/MetricsGrimoire/MailingListStats).
See https://github.com/MetricsGrimoire/CVSAnalY/issues/63 for discussion.

Further more to save the seconds is 
a) more efficient in database storage (int vs. char / varchar)
b) better usable in calculations in programing (calculation instead of string parsing)

@linzhp did you test it? Does it work for you?

**Comment by andygrunwald** [comment]
Any updates here @jgbarah @sduenas @linzhp ?
Can i merge this?

**Comment by linzhp** [comment]
I just tested it, it works. Just a side comment, the time zone information are not always reliable, as when a commit is imported from Subversion to Git, the time zone is always +0000. Not a bug in this PR, but something we need to pay attention to when we want to use time zone information.

**Comment by andygrunwald** [comment]
Is there a way to derect migrations from Subversion to Mark those commits?

Am Montag, 28. April 2014 schrieb Zhongpeng Lin :

**Comment by linzhp** [comment]
Yes, those commits often has a string "git-svn" in the commit message.

**Comment by andygrunwald** [comment]
I think we should integrate a feature like this (as a Extension?), but this
should be separated from the timezone feature.
But good point Zhongpeng!

Am Dienstag, 29. April 2014 schrieb Zhongpeng Lin :

**Comment by sduenas** [comment]
Sorry for not responding sooner. I've been busy these days.
Thanks to @andygrunwald for this cool feature and to @linzhp for you contribution.
Merged in 404d43d

**Comment by andygrunwald** [comment]
Thanks @sduenas!
Regarding the git-svn bridge, mentioned by @linzhp i created a new feature ticket: https://github.com/MetricsGrimoire/CVSAnalY/issues/83

**Pull request closed without merging**
